default:
  image: node:latest
stages:
  - build
  - deploy
  - upload to cdn
  - flushcache

cache:
  paths:
    - ./node_modules/

build:
  stage: build
  script:
    - npm i -g pnpm
    - pnpm install --no-frozen-lockfile
    - pnpm run build 
  artifacts:
    paths:
      - ./dist/

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-keyscan -p 4242 hidden >> ~/.ssh/known_hosts
  script:
    - rsync -e 'ssh -p 4242' -atv --delete --progress ./dist  ubuntu@hidden:/home/ubuntu/tmp/2023blobing
    - ssh -p 4242 ubuntu@hidden bash /home/ubuntu/2023blobing/runfronted.sh

upload to cdn:
  stage: upload to cdn
  image: rclone/rclone
  script:
    - rclone -P --config ./rclone/rclone.conf sync ./dist/ sendss3:public-cdn-1309039959/blobingcdn


flushcache:
  stage: flushcache
  image: python:alpine
  script:
    - cd python-flushcache
    - python -m pip install -r requirements.txt
    - python main.py
